name: CI for Github

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        coq_version: ["8.16"]
        os: ["ubuntu-latest"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
